name: release and publish to GPR.
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check version
        id: check_version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
      - name: Check pre
        id: check_pre
        run: echo ::set-output name=PRE::$(node -p "require('./package.json').ricohLsSdk.preRelease")   
      - name: Create Release
        id: create_release
        if: steps.check_pre.outputs.PRE == '' || steps.check_pre.outputs.PRE == 'undefined'        
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check_version.outputs.VERSION }}
          release_name: v${{ steps.check_version.outputs.VERSION }}
          body: v${{ steps.check_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Create Pre Release
        id: create_pre_release
        if: steps.create_release.conclusion == 'skipped'
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.check_version.outputs.VERSION }}-${{ steps.check_pre.outputs.PRE }}
          release_name: v${{ steps.check_version.outputs.VERSION }}-${{ steps.check_pre.outputs.PRE }}
          body: v${{ steps.check_version.outputs.VERSION }}
          draft: false
          prerelease: true